# Generated by Django 5.0.6 on 2024-06-05 09:20

from django.db import migrations


def set_username_to_email(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        user.username = user.email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240605_1119'),
    ]

    operations = [
        migrations.RunPython(set_username_to_email),
    ]