# Generated by Django 5.0.6 on 2024-06-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240605_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
