# Generated by Django 5.0.6 on 2024-07-09 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_comment_section_and_more'),
        ('manual', '0005_section_manual_sect_title_e93e2b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manual.subsection'),
        ),
    ]
