# Generated by Django 5.0.6 on 2024-06-02 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_contentversion_author_subsection_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manual.section'),
        ),
    ]
