# Generated by Django 5.0.6 on 2024-06-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_alter_subsection_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='css_path',
            field=models.CharField(blank=True, null=True),
        ),
    ]
