# Generated by Django 5.0.6 on 2024-06-21 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_alter_section_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['title'], name='manual_sect_title_e93e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['created_at'], name='manual_sect_created_e4eae0_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['updated_at'], name='manual_sect_updated_5b0212_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['section'], name='manual_subs_section_b27a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['parent'], name='manual_subs_parent__fbdd71_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['title'], name='manual_subs_title_ec24f9_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['created_at'], name='manual_subs_created_62aad4_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['updated_at'], name='manual_subs_updated_36ae0b_idx'),
        ),
    ]
